#include "main.h"

#include <stdio.h>
#include <stdlib.h>


#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
#include "images/beeStart.h"
#include "images/beeEnd.h"
#include "images/beeGame.h"
#include "images/beeCharacter.h"
#include "images/background.h"
#include "images/water.h"
#include "images/flower.h"
#include "images/beeWins.h"
/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};


int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //

  REG_DISPCNT = MODE3 | BG2_ENABLE;
 

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  drawFullScreenImageDMA(beeStart);

struct bee b;
b.row = randint(20, 140);
b.col = 0;
b.height = 20;
b.width = 20;
b.lifeCount = 3;

struct flower f;
f.row = randint(20, 140);
f.col = 220;
f.width = 20;
f.height = 20; 

struct drop d1, d2, d3, d4, d5, d6;
 
d1.col = 40;
d1.row = 120;
d1.height = 20;
d1. width = 20; 

d2.col = 80;
d2.row = 60;
d2.height = 20;
d2. width = 20;  

d3.col = 100;
d3.row = 0;
d3.height = 20;
d3. width = 20;  

d4.col = 140;
d4.row = 70;
d4.height = 20;
d4. width = 20;  

d5.col = 160;
d5.row = 100;
d5.height = 20;
d5. width = 20;

d6.col = 180;
d6.row = 0;
d6.height = 20;
d6. width = 20;




  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    waitForVBlank();

    switch (state) {
      case START:
      // undrawImageDMA(b.row, b.col, b.width, b.height,  beeStart);
      // undrawImageDMA(d1.row,d1.col, d1.width, d1.height, beeStart);
      // undrawImageDMA(d2.row,d2.col, d2.width, d2.height, beeStart);
      // undrawImageDMA(d3.row,d3.col, d3.width, d3.height, beeStart);
      // undrawImageDMA(d4.row,d4.col, d4.width, d4.height, beeStart);
      // undrawImageDMA(d5.row,d5.col, d5.width, d5.height, beeStart);
      // undrawImageDMA(d6.row,d6.col, d6.width, d6.height, beeStart);
      // undrawImageDMA(f.row, f.col, f.width, f.height, beeStart);
    
        drawString(5, 10 , "Help bee get to the ", GREEN);
        drawString(15, 10 , "flower !", GREEN);
        drawString(80, 100, "Press Enter to start", GREEN);


         if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
           drawFullScreenImageDMA(background);
           state = PLAY;
          
        }
        break;


      case PLAY:


      ///RESET??????


 ////////UNDRAW//////////



      undrawImageDMA(b.row, b.col, b.width, b.height, background);
      undrawImageDMA(d1.row,d1.col, d1.width, d1.height, background);
      undrawImageDMA(d2.row,d2.col, d2.width, d2.height, background);
      undrawImageDMA(d3.row,d3.col, d3.width, d3.height, background);
      undrawImageDMA(d4.row,d4.col, d4.width, d4.height, background);
      undrawImageDMA(d5.row,d5.col, d5.width, d5.height, background);
      undrawImageDMA(d6.row,d6.col, d6.width, d6.height, background);

 
 
 
 //////Control the bee/////

      if(KEY_DOWN(BUTTON_DOWN, currentButtons)){
        if (b.row + 22 > 140) {
         b.row = 140;
        } else {
          b.row = b.row + 2;
        }
      }
      if(KEY_DOWN(BUTTON_UP, currentButtons)){
        if (b.row -2 < 0) {
          b.row = 0;
        }else {
          b.row = b.row - 2;

        }
    
      }
      if(KEY_DOWN(BUTTON_LEFT, currentButtons)){
        if (b.col -2 <= 0) {
          b.col = 0;
        }else {
          b.col = b.col - 2;

        }
        
      }
      if(KEY_DOWN(BUTTON_RIGHT, currentButtons)){
        if (b.col + 2 >= 220) {
          b.col = 220;
        }else {
          b.col = b.col + 2;

        }
      }

//////COllissions with water//////////////////////

if( waterCollision(d1, b) || waterCollision(d2, b) || waterCollision(d3, b)
|| waterCollision(d4, b) || waterCollision(d5, b) || waterCollision(d6, b)){
  if (b.lifeCount  == 1 ){
    drawFullScreenImageDMA(beeEnd);
    state = LOSE;
    break;
  }

  drawFullScreenImageDMA(background);

  b.lifeCount --;

  // REINIT///

  b.col = 0;
  b.row = randint(20, 140);

  
}
/////////Colission with Flower////
if(flowerCollision(f,b)){
  drawFullScreenImageDMA(beeWins);
  state = WIN;
  break;
}


///// Movement of water drops////////////////////
if(d1.row + 1 > 160){
  d1.row = -20;
}else{
  d1.row += 1;
}

if(d2.row + 1 > 160){
  d2.row = -20;
}else{
  d2.row += 1;
}

if(d3.row + 1 > 160){
  d3.row = -20;
}else{
  d3.row += 1;
}

if(d4.row + 2 > 160){
  d4.row = -20;
}else{
  d4.row += 2;
}

if(d5.row + 1 > 160){
  d5.row = -20;
}else{
  d5.row += 1;
}

if(d6.row + 2 > 160){
  d6.row = 0;
}else{
  d6.row += 2;
}

///Drawing Objects///////

      drawImageDMA(b.row, b.col, b.width, b.height, beeCharacter);
      drawImageDMA(f.row, f.col, f.width, f.height, flower);

      
      drawImageDMA(d1.row, d1.col, d1.width, d1.height, water);
      drawImageDMA(d2.row, d2.col, d2.width, d2.height, water);
      drawImageDMA(d3.row, d3.col, d3.width, d3.height, water);
      drawImageDMA(d4.row, d4.col, d4.width, d4.height, water);
      drawImageDMA(d5.row, d5.col, d5.width, d5.height, water);
      drawImageDMA(d6.row, d6.col, d6.width, d6.height, water);
      
      drawLifeCount(0,150,b.lifeCount, WHITE);
        
        break;

        ///////////WIN//////////////////////



      case WIN:
      // undrawImageDMA(b.row, b.col, b.width, b.height, beeWins);
      // undrawImageDMA(f.row, f.col, f.width, f.height, beeWins);
      // undrawImageDMA(d1.row,d1.col, d1.width, d1.height, beeWins);
      // undrawImageDMA(d2.row,d2.col, d2.width, d2.height, beeWins);
      // undrawImageDMA(d3.row,d3.col, d3.width, d3.height, beeWins);
      // undrawImageDMA(d4.row,d4.col, d4.width, d4.height, beeWins);
      // undrawImageDMA(d5.row,d5.col, d5.width, d5.height, beeWins);
      // undrawImageDMA(d6.row,d6.col, d6.width, d6.height, beeWins);

      drawString(10,5,"Congratulations !", PURPLE);
      drawString(20,5,"You Won !", PURPLE);
    
      drawString(140,0,"Enter back to play again", PURPLE);


      if(KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)){
        drawFullScreenImageDMA(background);
        // renintilise
        b.col = 0;
        b.row  = randint(20, 140);
        b.lifeCount = 3;

        f.row = randint(20, 140);
        state = PLAY;
      
      }

        break;
      case LOSE:


      // undrawImageDMA(b.row, b.col, b.width, b.height,    beeEnd);
      // undrawImageDMA(d1.row,d1.col, d1.width, d1.height, beeEnd);
      // undrawImageDMA(d2.row,d2.col, d2.width, d2.height, beeEnd);
      // undrawImageDMA(d3.row,d3.col, d3.width, d3.height, beeEnd);
      // undrawImageDMA(d4.row,d4.col, d4.width, d4.height, beeEnd);
      // undrawImageDMA(d5.row,d5.col, d5.width, d5.height, beeEnd);
      // undrawImageDMA(d6.row,d6.col, d6.width, d6.height, beeEnd);
      // undrawImageDMA(f.row, f.col, f.width, f.height, beeEnd);

      


      drawString(60, 20, "Press Enter to PLAY again", RED);
        
      if(KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)){
        drawFullScreenImageDMA(background);
        // renintilise
        b.col = 0;
        b.row  = randint(20, 140);
        b.lifeCount = 3;

        f.row =randint(20, 140);
        state = PLAY;
      
      }
        break;
    }

     if(KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)){

        b.row =randint(20, 140);
        b.col = 0;
        b.lifeCount = 3;

        f.row = randint(20, 140);
        drawFullScreenImageDMA(beeStart);
        state = START;


      }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}



int waterCollision(struct drop drop, struct bee bee) {
    
    if (drop.row + drop.height >= bee.row && drop.row <= bee.row + bee.height &&
        drop.col + drop.width >= bee.col && drop.col <= bee.col + bee.width) {
        return 1; 
    }
    return 0; 
}
int flowerCollision(struct flower flower, struct bee bee) {
    
    if (flower.row + flower.height >= bee.row &&flower.row <= bee.row + bee.height &&
       flower.col + flower.width >= bee.col && flower.col <= bee.col + bee.width) {
        return 1;
       } 
    return 0; 
}



void drawLifeCount(int x, int y, int lifeCount, int color) {
    char buffer[20]; 
    sprintf(buffer, "Life Remaining: %d", lifeCount);
    drawString(x, y, buffer, color);
}

